### ISSUE TITLE
JavaScript backend: not properly reporting some exceptions

### ISSUE THREAD

**Issue by pgbovine** [pgbovine/OnlinePythonTutor#101]
This code ...

```javascript
var y = Object.create(5);
```

throws an exception in node but doesn't seem to trigger one in the JS visualization. ergh

```
$ node
> var y = Object.create(5);
TypeError: Object prototype may only be an Object or null
    at Function.create (native)
    at repl:1:16
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
```

Also:

```javascript
var assert = require('assert');

assert(true);
assert(true);
assert(false); // not failing here either with a proper error message
assert(true);
assert(true);
```

**Comment by pgbovine** [comment]
fixed!
