### ISSUE TITLE
v5-error while trying to run webpack

### ISSUE THREAD

**Issue by JahowChen** [pgbovine/OnlinePythonTutor#171]
I'm quite sure that everything has been installed properly(including phantomjs and phantomjs), but when I try to run webpack, error occurs. Please help.
```
$ sudo npm run webpack

> v5-unity@1.0.0 webpack /home/jahow/v5
> webpack --devtool sourcemap --progress --colors --watch


/home/jahow/v5/webpack.config.js:21
/tests/frontend-regression-tests/ && make micro", (error, stdout, stderr) => {
                                                                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/usr/local/lib/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

**Comment by habibieeddien** [comment]
@JahowChen You should edit `webpack.config.js` on `line 21`

`exec("cd SOME/YOUR/PATH/tests/frontend-regression-tests/ && make micro", (error, stdout, stderr)`

I was succeed after change the line code.
