### ISSUE TITLE
unknown error with rawinput with a type parameter

### ISSUE THREAD

**Issue by pgbovine** [pgbovine/OnlinePythonTutor#98]
e.g.,:

```python
x = raw_input(int)
```

also, similarly:

```python
max=raw_input(max)
```

(so not just with a type parameter, eek)

**Comment by pgbovine** [comment]
Ah, I see, builtin types and functions aren't JSON serializable ...

```python
max=raw_input(max)
```

```
Traceback (most recent call last):
  File "/Users/pgbovine/anaconda/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/pgbovine/anaconda/lib/python2.7/site-packages/bottle.py", line 1729, in wrapper
    rv = callback(*a, **ka)
  File "bottle_server.py", line 45, in get_exec
    json_finalizer)
  File "/Users/pgbovine/Dropbox/opt-git/OnlinePythonTutor/v3/pg_logger.py", line 1405, in exec_script_str_local
    return logger.finalize()
  File "/Users/pgbovine/Dropbox/opt-git/OnlinePythonTutor/v3/pg_logger.py", line 1351, in finalize
    return self.finalizer_func(self.executed_script, self.trace)
  File "bottle_server.py", line 36, in json_finalizer
    json_output = json.dumps(ret, indent=None)
  File "/Users/pgbovine/anaconda/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/Users/pgbovine/anaconda/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/pgbovine/anaconda/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/Users/pgbovine/anaconda/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <built-in function max> is not JSON serializable
```

**Comment by pgbovine** [comment]
OK fixed by converting the prompt in raw_input into a str() first before putting it into the trace
